export const TRAINEE_LOGIN_REQUEST = "TRAINEE_LOGIN_REQUEST";
export const TRAINEE_LOGIN_SUCCESS = "TRAINEE_LOGIN_SUCCESS";
export const TRAINEE_LOGIN_FAILURE = "TRAINEE_LOGIN_FAILURE";
export const TRAINEE_INITIAL_API_LOAD_SUCCESS =
    "TRAINEE_INITIAL_API_LOAD_SUCCESS";
export const TRAINEE_API_LOAD_INITIALIZE = "TRAINEE_API_LOAD_INITIALIZE";
export const TRAINEE_LOGOUT = "TRAINEE_LOGOUT";