export const S_ADMIN_LOGIN_REQUEST = "SUPER_ADMIN_LOGIN_REQUEST";
export const S_ADMIN_LOGIN_SUCCESS = "SUPER_ADMIN_LOGIN_SUCCESS";
export const S_ADMIN_LOGIN_FAILURE = "SUPER_ADMIN_LOGIN_FAILURE";
export const S_ADMIN_INITIAL_API_LOAD_SUCCESS =
    "S_ADMIN_INITIAL_API_LOAD_SUCCESS";
export const S_ADMIN_API_LOAD_INITIALIZE = "S_ADMIN_API_LOAD_INITIALIZE";
export const S_ADMIN_LOGOUT = "SUPER_ADMIN_LOGOUT";