// action types for getting Payment Package list
export const S_ADMIN_GET_PAYMENT_PACKAGE_LIST_REQUEST =
    "S_ADMIN_GET_PAYMENT_PACKAGE_LIST_REQUEST";
export const S_ADMIN_GET_PAYMENT_PACKAGE_LIST_SUCCESS =
    "S_ADMIN_GET_PAYMENT_PACKAGE_LIST_SUCCESS";
export const S_ADMIN_GET_PAYMENT_PACKAGE_LIST_FAILURE =
    "S_ADMIN_GET_PAYMENT_PACKAGE_LIST_FAILURE";
export const S_ADMIN_GET_PAYMENT_PACKAGE_LIST_NULL =
    "S_ADMIN_GET_PAYMENT_PACKAGE_LIST_NULL";

// action types for add Payment Package list
export const S_ADMIN_ADD_PAYMENT_PACKAGE_REQUEST = "S_ADMIN_ADD_PAYMENT_PACKAGE_REQUEST";
export const S_ADMIN_ADD_PAYMENT_PACKAGE_SUCCESS = "S_ADMIN_ADD_PAYMENT_PACKAGE_SUCCESS";
export const S_ADMIN_ADD_PAYMENT_PACKAGE_FAILURE = "S_ADMIN_ADD_PAYMENT_PACKAGE_FAILURE";

// action types for edit Payment Package list
export const S_ADMIN_UPDATE_PAYMENT_PACKAGE_REQUEST = "S_ADMIN_UPDATE_PAYMENT_PACKAGE_REQUEST";
export const S_ADMIN_UPDATE_PAYMENT_PACKAGE_SUCCESS = "S_ADMIN_UPDATE_PAYMENT_PACKAGE_SUCCESS";
export const S_ADMIN_UPDATE_PAYMENT_PACKAGE_FAILURE = "S_ADMIN_UPDATE_PAYMENT_PACKAGE_FAILURE";

// action types for get Payment Package by id 
export const S_ADMIN_GET_PAYMENT_PACKAGE_REQUEST = "S_ADMIN_GET_PAYMENT_PACKAGE_REQUEST";
export const S_ADMIN_GET_PAYMENT_PACKAGE_SUCCESS = "S_ADMIN_GET_PAYMENT_PACKAGE_SUCCESS";
export const S_ADMIN_GET_PAYMENT_PACKAGE_FAILURE = "S_ADMIN_GET_PAYMENT_PACKAGE_FAILURE";