// action types for getting profile data
export const TRAINEE_GET_PROFILE_REQUEST = "TRAINEE_GET_PROFILE_REQUEST";
export const TRAINEE_GET_PROFILE_SUCCESS = "TRAINEE_GET_PROFILE_SUCCESS";
export const TRAINEE_GET_PROFILE_FAILURE = "TRAINEE_GET_PROFILE_FAILURE";
export const TRAINEE_GET_PROFILE_NULL = "TRAINEE_GET_PROFILE_NULL";

// action types for updating profile information
export const TRAINEE_UPDATE_PROFILE_REQUEST = "TRAINEE_UPDATE_PROFILE_REQUEST";
export const TRAINEE_UPDATE_PROFILE_SUCCESS = "TRAINEE_UPDATE_PROFILE_SUCCESS";
export const TRAINEE_UPDATE_PROFILE_FAILURE = "TRAINEE_UPDATE_PROFILE_FAILURE";