// action types for getting exercise type list in the trainer panel
export const TRAINER_GET_EXERCISE_TYPE_LIST_REQUEST =
    "TRAINER_GET_EXERCISE_TYPE_LIST_REQUEST";
export const TRAINER_GET_EXERCISE_TYPE_LIST_SUCCESS =
    "TRAINER_GET_EXERCISE_TYPE_LIST_SUCCESS";
export const TRAINER_GET_EXERCISE_TYPE_LIST_FAILURE =
    "TRAINER_GET_EXERCISE_TYPE_LIST_FAILURE";
export const TRAINER_GET_EXERCISE_TYPE_LIST_NULL =
    "TRAINER_GET_EXERCISE_TYPE_LIST_NULL";

// action types for add exercise type list in the trainer panel
export const TRAINER_ADD_EXERCISE_TYPE_REQUEST =
    "TRAINER_ADD_EXERCISE_TYPE_REQUEST";
export const TRAINER_ADD_EXERCISE_TYPE_SUCCESS =
    "TRAINER_ADD_EXERCISE_TYPE_SUCCESS";
export const TRAINER_ADD_EXERCISE_TYPE_FAILURE =
    "TRAINER_ADD_EXERCISE_TYPE_FAILURE";

// action types for setting initial scroll position in the exercise type list component in the trainer panel
export const TRAINER_EXERCISE_TYPE_LIST_SET_SCROLL_POSITION =
    "TRAINER_EXERCISE_TYPE_LIST_SET_SCROLL_POSITION";