// action types for getting profile data
export const S_ADMIN_GET_PROFILE_REQUEST = "S_ADMIN_GET_PROFILE_REQUEST";
export const S_ADMIN_GET_PROFILE_SUCCESS = "S_ADMIN_GET_PROFILE_SUCCESS";
export const S_ADMIN_GET_PROFILE_FAILURE = "S_ADMIN_GET_PROFILE_FAILURE";
export const S_ADMIN_GET_PROFILE_NULL = "S_ADMIN_GET_PROFILE_NULL";

// action types for updating profile information
export const S_ADMIN_UPDATE_PROFILE_REQUEST = "S_ADMIN_UPDATE_PROFILE_REQUEST";
export const S_ADMIN_UPDATE_PROFILE_SUCCESS = "S_ADMIN_UPDATE_PROFILE_SUCCESS";
export const S_ADMIN_UPDATE_PROFILE_FAILURE = "S_ADMIN_UPDATE_PROFILE_FAILURE";