export const TRAINER_LOGIN_REQUEST = "TRAINER_LOGIN_REQUEST";
export const TRAINER_LOGIN_SUCCESS = "TRAINER_LOGIN_SUCCESS";
export const TRAINER_LOGIN_FAILURE = "TRAINER_LOGIN_FAILURE";
export const TRAINER_INITIAL_API_LOAD_SUCCESS =
    "TRAINER_INITIAL_API_LOAD_SUCCESS";
export const TRAINER_API_LOAD_INITIALIZE = "TRAINER_API_LOAD_INITIALIZE";
export const TRAINER_LOGOUT = "TRAINER_LOGOUT";