// action types for getting exercise type list
export const S_ADMIN_GET_EXERCISE_TYPE_LIST_REQUEST =
    "S_ADMIN_GET_EXERCISE_TYPE_LIST_REQUEST";
export const S_ADMIN_GET_EXERCISE_TYPE_LIST_SUCCESS =
    "S_ADMIN_GET_EXERCISE_TYPE_LIST_SUCCESS";
export const S_ADMIN_GET_EXERCISE_TYPE_LIST_FAILURE =
    "S_ADMIN_GET_EXERCISE_TYPE_LIST_FAILURE";
export const S_ADMIN_GET_EXERCISE_TYPE_LIST_NULL =
    "S_ADMIN_GET_EXERCISE_TYPE_LIST_NULL";

// action types for add exercise type list
export const S_ADMIN_ADD_EXERCISE_TYPE_REQUEST =
    "S_ADMIN_ADD_EXERCISE_TYPE_REQUEST";
export const S_ADMIN_ADD_EXERCISE_TYPE_SUCCESS =
    "S_ADMIN_ADD_EXERCISE_TYPE_SUCCESS";
export const S_ADMIN_ADD_EXERCISE_TYPE_FAILURE =
    "S_ADMIN_ADD_EXERCISE_TYPE_FAILURE";

// action types for setting initial scroll position in the exercise type list component
export const S_ADMIN_EXERCISE_TYPE_LIST_SET_SCROLL_POSITION =
    "S_ADMIN_EXERCISE_TYPE_LIST_SET_SCROLL_POSITION";