export const TRAINEE_PROFILE = "TRAINEE_PROFILE";
export const TRAINEE_PROFILE_FAILED = "TRAINEE_PROFILE_FAILED";
export const TRAINEE_PROFILE_SUCCESS = "TRAINEE_PROFILE_SUCCESS";
export const TRAINEE_PROFILE_UPDATE_SUCCESS = "TRAINEE_PROFILE_UPDATE_SUCCESS"