// action types for getting profile data
export const TRAINER_GET_PROFILE_REQUEST = "TRAINER_GET_PROFILE_REQUEST";
export const TRAINER_GET_PROFILE_SUCCESS = "TRAINER_GET_PROFILE_SUCCESS";
export const TRAINER_GET_PROFILE_FAILURE = "TRAINER_GET_PROFILE_FAILURE";
export const TRAINER_GET_PROFILE_NULL = "TRAINER_GET_PROFILE_NULL";

// action types for updating profile information
export const TRAINER_UPDATE_PROFILE_REQUEST = "TRAINER_UPDATE_PROFILE_REQUEST";
export const TRAINER_UPDATE_PROFILE_SUCCESS = "TRAINER_UPDATE_PROFILE_SUCCESS";
export const TRAINER_UPDATE_PROFILE_FAILURE = "TRAINER_UPDATE_PROFILE_FAILURE";